### ISSUE TITLE
Get-HPWarrantyEntitlement SOAP Request Timing out.

### ISSUE THREAD

**Issue by dotps1** [dotps1/HPWarranty#21]
It seems HP may have changed there warranty lookup process, again.  When using `Get-HPWarrantyEntitlement` the SOAP Request is timing out.

Here is the error from the SOAP Request Helper Function:
```
Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
```

also, the URLs are timing out (not sure they ever responded to a ping.)
```
PS C:\> ping services.isee.hp.com

Pinging services-isee.austin.hp.com [15.216.241.67] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 15.216.241.67:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

PS C:\> ping www.hp.com

Pinging www.hpgtm.nsatc.net [15.217.49.156] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 15.217.49.156:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```

**Comment by dotps1** [comment]
@kentucker5 if you'd be willing to install http://www8.hp.com/us/en/business-services/it-services.html?compURI=1078307#.VpmsFI-cH4Y on a HP Server and Fiddler so we can capture some output, we maybe able to solve this issue.  If you go back to #10 you'll see how we fixed it for the workstations.  My guess is the got rid of the ISEE as it was very cumbersome and have moved to the same method as the workstations.

thanks.

**Comment by dotps1** [comment]
@kentucker5, I'm working on fixing this issue, any chance you could send me a serialnumber/productnumber pair for an HP Server I can test with.  I only have workstations at my disposal.  You can email them to me directly if you are more comfortable doing that at Get-Alias@outlook.com.  Thanks.

**Comment by dotps1** [comment]
I've found something useful, there is a site that matches the HPInc warranty look up and using REST, its 'https://entitlement-hpe-ext.corp.hp.com/es/ES10_1/ESListener', now is use a template request with the HPInc cmdlet, and I tried reusing that for this one, but I am getting an Access Denied response.  So i'm a little stumped.  but ill keep digging.

**Comment by Hossy** [comment]
@dotps1, were you able to get a Fiddler trace off an HP server using the Support Assistant?  I'd like to help in any way I can.

**Comment by dotps1** [comment]
I did reply VIA email, must not have made it here.  I would love some help, I don't have any HP Servers to test with.  If you look at issue #10 you will see how it was fixed there, if we can do the same the servers, that would be awesome.  The method at the top of this thread doesn't return the amount of information the ISEE did or what the HPInc cmdlet does, so I don't really want to use it.

thanks for any help or insight you may have.

**Comment by Hossy** [comment]
Well, I have data centers full of them. :-)  The method you're referring to... do you mean ESListener?  I see your code was forked by @dillten, but he's using https://hpscm-pro.glb.itcs.hp.com/mobileweb/hpsupport.asmx/GetEntitlementDetails which doesn't return my Foundation Care warranties, so all my brand-spanking-new DL580 Gen9 servers don't show any active warranty using his method.

I'll test and see if the Support Assistant will work (let alone install) on a HP server and report back.

FYI -- all my HP servers are of the ProLiant variety.

**Comment by dillten** [comment]
That sucks about the G9's - hadn't tried it against my fleet of them. Was mainly focused on the G7's.

**Comment by Hossy** [comment]
@dillten, I'm sure it has to do with the way we're purchasing our servers now and less to do with the Gen9's themselves.  I think we're doing Care Packs on everything now and the normal HW warranty isn't present?  ... or something like that.  It's weird output I'm getting from https://hpscm-pro.glb.itcs.hp.com/mobileweb/hpsupport.asmx/GetEntitlementDetails, which doesn't match the output of the HTML-based Warranty Check page on the HPE site.

**Comment by dotps1** [comment]
Yeah, messing with the above method I had some Workstations return data, and some not.  So I think its way to unreliable.  Also, as I said it doesn't return near the amount of data.

If you look at how the `Get-HPIncWarrantyEntitlement` cmdlet works, it basically formats an xml template, and invokes a rest method to https://entitlement-ext.corp.hp.com/es/ES10_1/ESListener, and it returns the results.  The current way the `Get-HPWarrantyEntitlement` it has to format a registration request and then invoke a second request with SOAP using some data from the registration, its slow, but it was working.  After some digging I found this URL https://entitlement-hpe-ext.corp.hp.com/es/ES10_1/ESListener, if I use the same XML template as with the HPInc cmdlet, I do get a response, its just and Access Denied request.  The XML template has a hard coded username and password, its generic though, but I'm hoping that the Enterprise lookups just need a different credential pair.  And hopefully you can catch that with fiddler.

Please let me know what you find from you packet capture.  Thanks!

**Comment by Hossy** [comment]
Thanks!  That'll give me something for which to look.

**Comment by dotps1** [comment]
Just wondering if you made any progress?  Thanks.

**Comment by dotps1** [comment]
Bah, I still cannot find the right URL for HPE, getting a little frustrated.

**Comment by kelmansoury** [comment]
Hello. Me again.
Just to let you know that HP have once again changed their API. This time for HP Inc. If you re-open the old issue where we fixed it, I'll happily post the HTTP Request details for the new API that I acquired through the HP Support Assistant.

**Comment by dotps1** [comment]
I reopened issue #10 as well.

**Comment by kelmansoury** [comment]
Hi.
I'm not using the HP-Enterprise API any more with my C# implementation, but since I still have the code for it, while testing I did notice that if you don't put a time constrain on the request, it can take up to 5 min before eventually it works. It seems they have changed the resultant XML at the backend, but at least it works.
In that case, I suppose try setting the timeout value for 10 min or so and see what you get back for the registration request? The resultant XML for the registration request seems to have stayed the same, but not for the entitlement one.

**Comment by dotps1** [comment]
thanks for the info, 5 minutes is crazy lol.

**Comment by beanska** [comment]
@dotps1 @kelmansoury After increasing the timeout I am still not able to perform a registration. I am having no luck finding a source to capture with Fiddler. The only software I could find that leverages services.isee.hp.com is HP Insight Remote Support and that costs $$$.

**Comment by dotps1** [comment]
Yeah, I had the same experience, still did not work.

HP, what a bunch of bastards.

**Comment by dotps1** [comment]
Fixed with merge from @beanska, this is NOT published on the gallery yet, i still need to get some Help written up and some more testing.  I also added PSCredential support for use with the $ComputerName parameter.
